create table scores
(
    pk              int8 generated by default as identity,
    id              varchar(50) not null,
    name            varchar(50),
    score           float8,
    registration_pk int8,
    primary key (pk),
    foreign key (registration_pk) references registrations on delete cascade
)