create table registrations
(
    pk         int8 generated by default as identity,
    id         varchar(50) not null unique,
    course_pk  int8,
    student_pk int8,
    primary key (pk),
    foreign key (course_pk) references courses on delete cascade,
    foreign key (student_pk) references students on delete cascade
);
CREATE UNIQUE INDEX idx_unique_student_and_course ON registrations (student_pk, course_pk);