create table students
(
    pk         int8 generated by default as identity,
    id         varchar(50) not null unique,
    student_id varchar(50) not null unique,
    name       varchar(50),
    last_name  varchar(50),
    primary key (pk)
);